### ISSUE TITLE
2.2.0 doesn't work

### ISSUE THREAD

**Issue by misha-erm** [lrlna/pino-colada#43]
Hello, 
I tried to update from 2.1.0 to 2.2.0 and pino-colada fails with the error `env: node\r: No such file or directory`.

Small googling revealed it's connected with line endings: https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo

Thank you

OS: macOs Big Sur 11.2.3
node: 14.17.6

**Comment by sanjom** [comment]
Can we merge the PR and fix the line endings? Experiencing the same problem...

**Comment by lrlna** [comment]
I just published a patch from my mac instead of my windows machine, which uses LF. This should work for you.

Are you all using yarn? It seems like there is a bug in that package manager supporting publishes from different OS's. `npm` normalises line endings in `package.json`, allowing maintainers to publish no matter their environment.

**Comment by misha-erm** [comment]
New version works OK, thank you.

> Are you all using yarn?

Yes, I do) haven't tried it with npm
